### ISSUE TITLE
Proposta norma nomi file e cartelle

### ISSUE THREAD

**Issue by Archetipo95** [Spaghetti-Code-G6/Documenti#21]
Ci serve uno standard da usare per tutti i file e le cartelle contenute in questa repo.

Le possibilità sono:

- Camel Case: **questoEUnEsempio/fileNuovo.tex**
- Pascal Case: **QuestoEUnEsempio/FileNuovo.tex**
- CS con trattini: **questo-E-Un-Esempio/file-Nuovo.tex**
- PC con trattini: **Questo-e-un-esempio/File-Nuovo.tex**

_P.S.1
Se avete altre proposte fatele pure nei commenti sotto._
_P.S.2
Una seconda proposta di norma è quella di NON usare accenti nei nomi dei file e nei nomi delle cartelle._

**Comment by rizzostefano** [comment]
🐫 case

**Comment by Ubriacopo** [comment]
🌞
      
      
.... .. . . . . .. . . ..🐫  . .. . .... . . :desert_island:... . .. . . .. .... . ... . .. ..
..... . ..........    ....     . .    ...... .. .. .    .. ...   . ... ....... ....  . .. . ... .. ... . . .
......... ....  ... ... .. .... .. .. ... ..    . ...... ... .. . .. . 🐫 .. .. ......... ..  .. . ..........

**Comment by danielcontro** [comment]
snake_case?

**Comment by Archetipo95** [comment]
Ecco una prova.
Ho cambiato il nome alle cartelle perché erano abbastanza illeggibili.
![image](https://user-images.githubusercontent.com/11798239/102714339-27998200-42ce-11eb-897d-f9d5e52f859f.png)

Quindi la proposta è:

- scrivere i nome delle cartelle con l'iniziale maiuscola, gli spazi e gli accenti
- scrivere i nomi dei file con l'iniziale minuscola (quindi non devono iniziare con un numero), camelCase e senza accenti
